// Generated by CoffeeScript 1.7.1
(function() {
  window.onload = function() {
    var canvas, ctx, fillColor, height, rotationFrame, setup, width, x, xDir, y, yDir;
    canvas = null;
    ctx = null;
    x = 0;
    y = 0;
    width = 0;
    height = 0;
    radian = 0;
    radianStep = 0;
    xDir = +1;
    yDir = +1;
    fillColor = 0; 
    setup = function() {
      canvas = document.getElementById('the-canvas');
      ctx = canvas.getContext('2d');
      x = 0;
      y = 0;
      width = 20;
      height = 20;
      fillColor = {
        red: {
          value: 60
        },
        green: {
          value: 190
        },
        blue: {
          value: 10
        },
        toRGBString: function() {
          return "rgb(" + this.red.value + ", " + this.green.value + ", " + this.blue.value + ")";
        }
      };
      return rotationFrame();
    };
    rotationFrame = function() {	
      ctx.fillStyle = fillColor.toRGBString();
      ctx.beginPath();
      ctx.globalCompositeOperation = "copy";
//	  ctx.clearRect(0, 0, canvas.width, canvas.height);
	  ctx.arc(x, y, width, 0, 2 * Math.PI, true);
//    ctx.stroke();
      ctx.fill();
//	  ctx.closePath();
      if (x + width >= canvas.width) {
        xDir = -10;
      } else if (x - width <= 0) {
        xDir = +10;
      }
      if (y + height >= canvas.height) {
        yDir = -10;
      } else if (y - height <= 0) {
        yDir = +10;
      }
      x += xDir;
      y += yDir;	
	  setTimeout(rotationFrame, 100);
//    return requestAnimationFrame(rotationFrame);
    };
    return setup();
  };

}).call(this);
