// Generated by CoffeeScript 1.7.1
(function() {
  window.onload = function() {
    var canvas, ctx, fillColor, radius, ballMotionFrame, setup, x, xDir, y, yDir;
    canvas = null;
    ctx = null;
    x = 0;
    y = 0;
	radius = 20;
    radian = 2 * Math.PI;
    xDir = +1;
    yDir = +1;
    fillColor = 0; 
    setup = function() {
      canvas = document.getElementById('the-canvas');
      ctx = canvas.getContext('2d');
      x = 0;
      y = 0;
      fillColor = {
        red: {
          value: 60
        },
        green: {
          value: 190
        },
        blue: {
          value: 10
        },
        toRGBString: function() {
          return "rgb(" + this.red.value + ", " + this.green.value + ", " + this.blue.value + ")";
        }
      };
      return ballMotionFrame();
    };
    ballMotionFrame = function() {	
      ctx.fillStyle = fillColor.toRGBString();
      ctx.beginPath();
      ctx.globalCompositeOperation = "copy"; /* equivalent to the method in the row below, choose the one you prefer */
//	  ctx.clearRect(0, 0, canvas.width, canvas.height);
	  ctx.arc(x, y, radius, 0, radian, true); 
      ctx.fill();
      if (x + radius >= canvas.width) {
        xDir = -10;
      } else if (x - radius <= 0) {
        xDir = +10;
      }
      if (y + radius >= canvas.height) {
        yDir = -10;
      } else if (y - radius <= 0) {
        yDir = +10;
      }
      x += xDir;
      y += yDir;  
	  setTimeout(ballMotionFrame, 25); /* equivalent to the method in the row below, choose the one you prefer */
//    return requestAnimationFrame(ballMotionFrame);		  
    };
    return setup();
  };

}).call(this);
